// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5IYjdWhSTgPw-9duVnXnmTLx0yRdY9yA',
    appId: '1:1068453648041:web:483d65bfbda20527823bb8',
    messagingSenderId: '1068453648041',
    projectId: 'auth-julia',
    authDomain: 'auth-julia.firebaseapp.com',
    storageBucket: 'auth-julia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTVCCzKBz75CKchC9bjGJwTUaxYbmnUK0',
    appId: '1:1068453648041:android:aeef2ffd1aafa378823bb8',
    messagingSenderId: '1068453648041',
    projectId: 'auth-julia',
    storageBucket: 'auth-julia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwT7b7XSiLfS7npuliBEGVshhEqFxEdyg',
    appId: '1:1068453648041:ios:2413efa33fbb7c44823bb8',
    messagingSenderId: '1068453648041',
    projectId: 'auth-julia',
    storageBucket: 'auth-julia.firebasestorage.app',
    iosBundleId: 'com.example.apkAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwT7b7XSiLfS7npuliBEGVshhEqFxEdyg',
    appId: '1:1068453648041:ios:2413efa33fbb7c44823bb8',
    messagingSenderId: '1068453648041',
    projectId: 'auth-julia',
    storageBucket: 'auth-julia.firebasestorage.app',
    iosBundleId: 'com.example.apkAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5IYjdWhSTgPw-9duVnXnmTLx0yRdY9yA',
    appId: '1:1068453648041:web:5a99ffe6b843383a823bb8',
    messagingSenderId: '1068453648041',
    projectId: 'auth-julia',
    authDomain: 'auth-julia.firebaseapp.com',
    storageBucket: 'auth-julia.firebasestorage.app',
  );
}
