// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQU6y2g8Ly10A1hgaBflQj3ojKHN6qMlI',
    appId: '1:25634296669:web:a92c0c780942410dddceb4',
    messagingSenderId: '25634296669',
    projectId: 'notes-6a15f',
    authDomain: 'notes-6a15f.firebaseapp.com',
    storageBucket: 'notes-6a15f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_W70QjZBnDrTn-B6UosHR0Xfqzxcnf8A',
    appId: '1:25634296669:android:7cb0af0491d54e94ddceb4',
    messagingSenderId: '25634296669',
    projectId: 'notes-6a15f',
    storageBucket: 'notes-6a15f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2T3b67PCu2RUkS3YORYJI8O_jbuOCg20',
    appId: '1:25634296669:ios:7df0a31770663252ddceb4',
    messagingSenderId: '25634296669',
    projectId: 'notes-6a15f',
    storageBucket: 'notes-6a15f.firebasestorage.app',
    iosBundleId: 'com.example.apkNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2T3b67PCu2RUkS3YORYJI8O_jbuOCg20',
    appId: '1:25634296669:ios:7df0a31770663252ddceb4',
    messagingSenderId: '25634296669',
    projectId: 'notes-6a15f',
    storageBucket: 'notes-6a15f.firebasestorage.app',
    iosBundleId: 'com.example.apkNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQU6y2g8Ly10A1hgaBflQj3ojKHN6qMlI',
    appId: '1:25634296669:web:ff257e6d644006ddddceb4',
    messagingSenderId: '25634296669',
    projectId: 'notes-6a15f',
    authDomain: 'notes-6a15f.firebaseapp.com',
    storageBucket: 'notes-6a15f.firebasestorage.app',
  );
}
